### ISSUE TITLE
Can't install - unresolved packages

### ISSUE THREAD

**Issue by horejsek** [tarpas/pytest-testmon#23]
I can see that there is requirements.txt but it's not used in setup.py. Instead in setup.py is different set of dependency. Unfortunatelly I can't install it because of `coverage_pth`, but I can install `coveragepy` from requirements.txt just allright.

Can you fix it or help me what I am doing wrong? By the way it's on Debian Wheezy with Python 2.7.

```
$ pip install pytest-testmon
Downloading/unpacking pytest-testmon
  Downloading pytest-testmon-0.6.tar.gz
  Running setup.py egg_info for package pytest-testmon
    
Downloading/unpacking pytest>=2.7.0,<2.9 (from pytest-testmon)
  Running setup.py egg_info for package pytest
    
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.7.1,<4.0 in ./src/coverage (from pytest-testmon)
Downloading/unpacking coverage-pth (from pytest-testmon)
  Running setup.py egg_info for package coverage-pth
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/michal.horejsek/build/coverage-pth/setup.py", line 9, in <module>
        rel_site_packages = sprem.group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/michal.horejsek/build/coverage-pth/setup.py", line 9, in <module>

    rel_site_packages = sprem.group(1)

AttributeError: 'NoneType' object has no attribute 'group'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/michal.horejsek/build/coverage-pth
Storing complete log in /home/michal.horejsek/.pip/pip.log
```

```
$ pip install coverage_pth
Downloading/unpacking coverage-pth
  Running setup.py egg_info for package coverage-pth
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/michal.horejsek/build/coverage-pth/setup.py", line 9, in <module>
        rel_site_packages = sprem.group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/michal.horejsek/build/coverage-pth/setup.py", line 9, in <module>

    rel_site_packages = sprem.group(1)

AttributeError: 'NoneType' object has no attribute 'group'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/michal.horejsek/build/coverage-pth
Storing complete log in /home/michal.horejsek/.pip/pip.log
```

**Comment by tarpas** [comment]
This is a bug in coverage_pth which we use to automatically enable tracking of subprocesses (automatically performing steps from http://nedbatchelder.com/code/coverage/subprocess.html) Could you report there?

What is you the result of

    from distutils import sysconfig
    pring sysconfig.get_python_lib()

at your system?

As a workaround you could remove coverage_pth from our setup.py and perform the subprocess configuration manually.

**Comment by horejsek** [comment]
Result is `/usr/lib/python2.7/dist-packages`.

Well, I though that you will redirect me to coverage_pth and I actually wanted to try report bug there but I couldn't find where. :-D Anyway there is still mix of setup.py and requirements.txt which is different.

**Comment by tarpas** [comment]
Well, it's a complex problem which we all hope coverage will solve and
maintain the solution..

**Comment by horejsek** [comment]
Cool. Works really well. :-)
