### ISSUE TITLE
Does not get path to database file correctly with "/tmp" as additional dir/arg

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#45]
```
% py.test project /tmp/envdir_tty
Traceback (most recent call last):
  File "…/pyenv/3.5.1/envs/tmp-3.5.1-2UJvnn/bin/py.test", line 9, in <module>
    load_entry_point('pytest', 'console_scripts', 'py.test')()
  File "…/Vcs/pytest/_pytest/config.py", line 49, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "…/Vcs/pytest/_pytest/vendored_packages/pluggy.py", line 727, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/Vcs/pytest/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/Vcs/pytest/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "…/Vcs/pytest/_pytest/vendored_packages/pluggy.py", line 599, in execute
    res = hook_impl.function(*args)
  File "…/Vcs/pytest-testmon/testmon/pytest_testmon.py", line 81, in pytest_cmdline_main
    init_testmon_data(config)
  File "…/Vcs/pytest-testmon/testmon/pytest_testmon.py", line 75, in init_testmon_data
    variant=variant)
  File "…/Vcs/pytest-testmon/testmon/testmon_core.py", line 150, in __init__
    self.init_connection()
  File "…/Vcs/pytest-testmon/testmon/testmon_core.py", line 172, in init_connection
    self.connection = sqlite3.connect(self.datafile)
sqlite3.OperationalError: unable to open database file
```

`self.datafile` ends up being `/.testmondata`.

Might be related to https://github.com/pytest-dev/pytest/issues/1594.

**Comment by blueyed** [comment]
I've left additional info at https://github.com/pytest-dev/pytest/issues/1594#issuecomment-225902013: using `py.test -c setup.cfg --custom-option foo` triggers it, but `py.test -c setup.cfg --custom-option=foo` works.

**Comment by tarpas** [comment]
Daniel, I'm very busy at the moment so I think you're on your own.. But I
plan a release in the future with and then I'll also look here. Thanks for
patience.

On Tue, Jun 14, 2016 at 4:38 PM, Daniel Hahler <notifications@github.com>
wrote:

> I've left additional info at pytest-dev/pytest#1594 (comment)
> <https://github.com/pytest-dev/pytest/issues/1594#issuecomment-225902013>:
> using py.test -c setup.cfg --custom-option foo triggers it, but py.test
> -c setup.cfg --custom-option=foo works.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tarpas/pytest-testmon/issues/45#issuecomment-225902358>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIQsNQxsYXS5InahTl59XZVUeTPCfKnks5qLrzfgaJpZM4IwHfM>
> .
>



-- 
Best,
Tibor
+421907266112
-----
www.infinit.sk - The Python development team
www.testmon.org  - taking automated Python tests to a new level

**Comment by blueyed** [comment]
It's an issue with pytest - if it gets accepted as a bug in the end, since `rootdir` ends up being `/`.
See https://github.com/pytest-dev/pytest/pull/1621 for a WIP-PR to address this.
Closing this issue here.

Glad to hear there will be a new release soon.
Thanks!
