### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by maxnordlund** [tarpas/pytest-testmon#68]
Hi, I got this weird error when using testmon and pytest-watcher together. Both work fine individually but as you can see below, they somehow interfere with each other.

The error is in testmon, hence the issue here. I'm stumped, and the really funny thing is that it used to work just a couple of days ago so I'm not sure what happened.

<details>
<summary>Terminal output
</summary>

```
$ ptw -- --testmon import_contacts
Running: py.test --testmon import_contacts
Traceback (most recent call last):
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/_pytest/config.py", line 58, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/testmon/pytest_testmon.py", line 107, in pytest_cmdline_main
    init_testmon_data(config)
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/testmon/pytest_testmon.py", line 98, in init_testmon_data
    variant=variant)
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/testmon/testmon_core.py", line 205, in __init__
    self.init_connection()
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/testmon/testmon_core.py", line 221, in init_connection
    self._check_data_version()
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/testmon/testmon_core.py", line 227, in _check_data_version
    self._write_attribute(self._DATA_VERSION_KEY, str(self.DATA_VERSION))
  File "/Users/maxno/.pyenv/versions/venvs/15a88226-efa3-11e6-afd5-475fa2145b46/lib/python3.6/site-packages/testmon/testmon_core.py", line 271, in _write_attribute
    [compressed_data_buffer, dataid])
sqlite3.OperationalError: database is locked
^C
$ pytest --testmon import_contacts/
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.6.0, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
Using --randomly-seed=1497255222
Django settings: referanza.settings.local_settings (from ini file)
testmon=True, changed files: 0, skipping collection of 0 items, run variant: default
rootdir: /Users/maxno/Code/referanza, inifile: pytest.ini
plugins: xdist-1.16.0, translations-1.0.4, timeout-1.2.0, testmon-0.9.5, reqs-0.0.5, regtest-0.15.1, randomly-1.1.2, notifier-1.0.0, mock-1.6.0, instafail-0.3.0, gitignore-1.3, django-3.1.2, datadir-ng-1.1.0, cov-2.5.1, bpdb-0.1.4, bdd-2.18.2, hypothesis-3.11.1, celery-4.0.2
collected 11 items

import_contacts/tests/test_inner_serializer_meta_class.py ......
import_contacts/tests/test_fuzzy_assertion.py ..
import_contacts/tests/test_import_session.py .
import_contacts/tests/test_phonenumber_validator.py ..

======================================================================================== 11 passed in 0.56 seconds =========================================================================================
$
```

</details>

**Comment by blueyed** [comment]
https://github.com/tarpas/pytest-testmon/pull/69 should fix this.

The problem is that `init_connection` gets called with pytest-watch's `--collect-only` run.

It should a) get closed before the 2nd / real run, and b) not being initialized/read at all, since ptw uses `plugins=collect_config_plugin`, and testmon should not do any setup then.

**Comment by maxnordlund** [comment]
Thank you ❤️

**Comment by blueyed** [comment]
@maxnordlund 
Have you tested it?
Can you provide feedback there then, please?

**Comment by maxnordlund** [comment]
Yes, and it works as far as I can see.

**Comment by tarpas** [comment]
Thanks guys. I'll have a look today or tomorrow.

**Comment by maestro-brentpanther** [comment]
I found a similar issue when running with xdist. Since 0.9.5 I get the "database is locked" error when it is writing the stored_data_version, when executing `_check_data_version()` from `init_connection()`. Downgrading to 0.9.4 works fine.
