### ISSUE TITLE
Assert item.nodeid not in self.collection_ignored

### ISSUE THREAD

**Issue by wrvdklooster** [tarpas/pytest-testmon#88]
For some reason I always get this error after I changed something in my code and run testmon again.

The initial run for creating the database works fine.

```
$ pytest --testmon
Test session starts (platform: darwin, Python 3.5.2, pytest 3.3.2, pytest-sugar 0.9.0)
metadata: {'Plugins': {'celery': '4.1.0', 'xdist': '1.22.0', 'django': '3.1.2', 'html': '1.16.1', 'forked': '0.2', 'mock': '1.6.3', 'metadata': '1.5.1', 'django-webtest': '1.9.2', 'testmon': '0.9.7', 'sugar': '0.9.0', 'cov': '2.5.1', 'pep8': '1.0.6', 'factoryboy': '1.3.1'}, 'Platform': 'Darwin-17.4.0-x86_64-i386-64bit', 'JAVA_HOME': '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home', 'Packages': {'pytest': '3.3.2', 'py': '1.5.2', 'pluggy': '0.6.0'}, 'Python': '3.5.2'}
Django settings: prj.test_settings (from ini file)
testmon=True, changed files: order/views.py, skipping collection of 1728 items, run variant: default
rootdir: /Users/Richard/workspace/prj/python, inifile: setup.cfg
plugins: xdist-1.22.0, testmon-0.9.7, sugar-0.9.0, pep8-1.0.6, mock-1.6.3, metadata-1.5.1, html-1.16.1, forked-0.2, factoryboy-1.3.1, django-3.1.2, cov-2.5.1, django-webtest-1.9.2, celery-4.1.0
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/_pytest/main.py", line 142, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/_pytest/main.py", line 152, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/_pytest/main.py", line 685, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Richard/.pyenv/versions/3.5.2/envs/prj/lib/python3.5/site-packages/testmon/pytest_testmon.py", line 176, in pytest_collection_modifyitems
INTERNALERROR>     assert item.nodeid not in self.collection_ignored
```

**Comment by tarpas** [comment]
Thanks for reporting. It's probably interaction with some other pytest plugin. 

testmon is flagging some test module not to be collected (and executed) but some other plugin is adding it back in for execution. 

Which one of the plugin is active even without any command line option?

Do your test depend on all of the plugins mentioned or could you make your test suite at least collect and fail after collection with a reduced set of plugin-s? I'm not very familiar with many of them so I don't know which one is forcing collection of tests even if testmon marks them not to be collected.

**Comment by tarpas** [comment]
@wrvdklooster I pushed the fix to pypi., pytest-testmon v0.9.8 ..

**Comment by wrvdklooster** [comment]
It is working fine now. Thanks for the fix.
